import requests

data = [
	"rosvik/248.no",
	"rosvik/dotfiles",
	"rosvik/ntnu-proglab-arduino-zumo",
	"rosvik/ntnu-tdt4113-rpi-zumo",
	"rosvik/ntnu-tdt4145-database-project",
	"rosvik/ntnu-tfe4102-rapport-lab4",
	"rosvik/string.248.no",
	"dylanaraps/awesome-shell",
	"dylanaraps/bin",
	"dylanaraps/BlazeBot",
	"dylanaraps/bush",
	"dylanaraps/COS10005",
	"dylanaraps/COS10009",
	"dylanaraps/crayon",
	"dylanaraps/discord-open-source",
	"dylanaraps/discord-selena",
	"dylanaraps/dlink-ssid-bypass",
	"dylanaraps/dotfiles",
	"dylanaraps/dunst",
	"dylanaraps/dylanaraps.github.io-old",
	"dylanaraps/Flatabulous-wal",
	"dylanaraps/i3",
	"dylanaraps/i3-style",
	"dylanaraps/neofetch",
	"dylanaraps/neofetch-branding",
	"dylanaraps/nfu",
	"dylanaraps/nnn",
	"dylanaraps/official-bash-logo",
	"dylanaraps/openbox-patched",
	"x0rz/EQGRP",
	"x0rz/EQGRP_Lost_in_Translation",
	"x0rz/ssh-honeypot",
	"x0rz/tweetentropy",
	"QuadPiece/Black-Crunchyroll",
	"QuadPiece/club-quad",
	"QuadPiece/converter-thing",
	"QuadPiece/flask-blog",
	"QuadPiece/hugo-casper-two",
	"QuadPiece/LazyWebM",
	"QuadPiece/list-fm",
	"QuadPiece/logic",
	"QuadPiece/metrodeck",
	"QuadPiece/node-test",
	"QuadPiece/openings-helper",
	"QuadPiece/pybench",
	"QuadPiece/quad-devices",
	"QuadPiece/Quad-Devices-Two",
	"QuadPiece/Quad-New-Tab",
	"QuadPiece/quad.moe",
	"QuadPiece/QuadFile",
	"QuadPiece/QuadFile-legacy",
	"QuadPiece/sickrage.github.io",
	"QuadPiece/TweetDeck-Stealth",
	"QuadPiece/youtube-checker"
]

for repo in data:
	url = "https://raw.githubusercontent.com/{}/master/README.md".format(repo)
	print(url)
	requests.post("http://localhost:3000/api/entries", data={'url': url})
